/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz_Ordenamientos;

import Ordenamiento_Balanceado.OrdenamientoBalanceado;
import Ordenamiento_Directo.OrdenamientoDirecto;
import Ordenamiento_Natural.OrdenamientoNatural;
import Ordenamiento_Polifase.OrdenamientoPolifase;
import com.csvreader.CsvReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.text.ParseException;
import java.util.Random;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author vladii
 */
public class interfaz_principal extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public interfaz_principal() {
        initComponents();
        new Tiempo();
        this.setLocationRelativeTo(null);
        
    }
    int tiempoTotal = 5;
    public class Tiempo {
        public Tiempo() {
            Timer timer = new Timer();
            timer.scheduleAtFixedRate(timerTask, 0, 1000);
        }
        TimerTask timerTask = new TimerTask() {
            public void run() {
                tiempoTotal++;
            }
        };
    }
    public String getTiempo(int segundos)
    {
        int horas =segundos/3600;
        int minutos =(segundos-(3600*horas))/60;
        int seg = segundos-((horas*3600)+(minutos*60));
        
        return String.format("%02d",horas) + "h:" + String.format("%02d",minutos) + "m:" + String.format("%02d",seg) + "s";
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        JButton_buscarArchivo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton_directa = new javax.swing.JRadioButton();
        jRadioButton_natural = new javax.swing.JRadioButton();
        jRadioButton_balanceada = new javax.swing.JRadioButton();
        jRadioButton_poliface = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton_numerico = new javax.swing.JRadioButton();
        jRadioButton_texto = new javax.swing.JRadioButton();
        jRadioButton_booleano = new javax.swing.JRadioButton();
        jRadioButton_fecha = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jButton_salir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel_mostrarTiempo = new javax.swing.JLabel();
        jLabel_direccion = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel_intercalacion = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel_campo = new javax.swing.JLabel();
        JButton_ordenarArchivo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel_mostrarCampo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel_tiempoReloj = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("ORDENAMIENTOS EXTERNOS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 11, 199, 26));

        JButton_buscarArchivo.setText("Buscar Archivo");
        JButton_buscarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_buscarArchivoActionPerformed(evt);
            }
        });
        getContentPane().add(JButton_buscarArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 197, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Ordenamientos:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 89, -1));

        jRadioButton_directa.setText("Intercalacion Directa");
        jRadioButton_directa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_directaActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton_directa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jRadioButton_natural.setText("Intercalacion Natural");
        jRadioButton_natural.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_naturalActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton_natural, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        jRadioButton_balanceada.setText("Intercalacion Balanceada");
        jRadioButton_balanceada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_balanceadaActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton_balanceada, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));

        jRadioButton_poliface.setText("Intercalacion Poliface");
        jRadioButton_poliface.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_polifaceActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton_poliface, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, -1, -1));

        jLabel2.setText("Campos");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jRadioButton_numerico.setText("Numerico");
        jRadioButton_numerico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_numericoActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton_numerico, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jRadioButton_texto.setText("Texto");
        jRadioButton_texto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_textoActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton_texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        jRadioButton_booleano.setText("Booleano");
        jRadioButton_booleano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_booleanoActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton_booleano, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));

        jRadioButton_fecha.setText("Fecha");
        jRadioButton_fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_fechaActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 43, 682, 136));

        jLabel8.setText("Ruta del Archivo:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 201, -1, -1));

        jButton_salir.setText("Salir");
        jButton_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_salirActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 410, 74, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_mostrarTiempo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel_mostrarTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 200, 20));

        jLabel_direccion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 600, 21));

        jLabel4.setText("Intecalacion:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel_intercalacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel_intercalacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 127, 18));

        jLabel6.setText("Nombre Archivo:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel_campo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel_campo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 127, 18));

        JButton_ordenarArchivo.setText("Ordenar Archivo");
        JButton_ordenarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_ordenarArchivoActionPerformed(evt);
            }
        });
        jPanel1.add(JButton_ordenarArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 219, -1));

        jLabel5.setText("Tiempo de Duracion:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 20));

        jLabel9.setText("Campo: ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, -1, -1));

        jLabel_mostrarCampo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel_mostrarCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 130, 20));

        jLabel7.setText("Tiempo Reloj:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel_tiempoReloj.setText("00h:00m:00s");
        jLabel_tiempoReloj.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel_tiempoReloj, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 90, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 226, 682, 181));

        jButton1.setText("Mostrar Registros Ordenados");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton_directaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_directaActionPerformed
        if (this.jRadioButton_natural.isSelected() || this.jRadioButton_balanceada.isSelected() || this.jRadioButton_poliface.isSelected() )
        {
            this.jRadioButton_natural.setSelected(false);
            this.jRadioButton_balanceada.setSelected(false);
            this.jRadioButton_poliface.setSelected(false);
            
        }
        this.jLabel_intercalacion.setText("Directa");
      
    }//GEN-LAST:event_jRadioButton_directaActionPerformed

    private void jRadioButton_numericoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_numericoActionPerformed
        if (this.jRadioButton_texto.isSelected() || this.jRadioButton_booleano.isSelected() || this.jRadioButton_fecha.isSelected())
        {
            this.jRadioButton_texto.setSelected(false);
            this.jRadioButton_booleano.setSelected(false);
            this.jRadioButton_fecha.setSelected(false);
        }
        this.jLabel_mostrarCampo.setText("Numerico");
    }//GEN-LAST:event_jRadioButton_numericoActionPerformed
    
    private void JButton_buscarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_buscarArchivoActionPerformed
        JFileChooser ventanaBusqueda = new JFileChooser();//Objeto ventana de busqueda
        ventanaBusqueda.setFileSelectionMode(JFileChooser.FILES_ONLY);//Tipo de busqueda
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos .csv", "csv");
        ventanaBusqueda.setFileFilter(filter);//Extenciones
        ventanaBusqueda.setMultiSelectionEnabled(true);//Seleccionar varios archivos
        int returnVal = ventanaBusqueda.showOpenDialog(null);//Condicional de aceptacion seleccion
        if(returnVal == JFileChooser.APPROVE_OPTION)
        {
            File archivo = ventanaBusqueda.getSelectedFile();
            jLabel_direccion.setText(archivo.getPath());
            this.jLabel_direccion.setText(archivo.getAbsolutePath());
            
            
            if(!new File(this.jLabel_direccion.getText()).exists())
            {
                this.jPanel1.setVisible(false);
            }
            else
            {
                File arch = new File(this.jLabel_direccion.getText());
                this.jLabel_campo.setText(arch.getName());
                
                int rango=0;
                try {
                    CsvReader leer = new CsvReader(this.jLabel_direccion.getText());
                    while (leer.readRecord()) rango++; leer.close();
                }catch (FileNotFoundException ex) {} catch (IOException ex) {}
                
            }
            
        }
        
        
    }//GEN-LAST:event_JButton_buscarArchivoActionPerformed
    
    
    private void JButton_ordenarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_ordenarArchivoActionPerformed
        
        long inicio = System.nanoTime();
        
        for (int i = 0; i < 1000; i++) {
            for (int j = 0; j < 1000; j++) {
                new Random().nextDouble();
            }
        }
        if(!new File(this.jLabel_direccion.getText()).exists())
        {
            JOptionPane.showMessageDialog(null, "Seleccione un Archovo .csv para Ordenarlo.", "Error !!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        else
        {
            int rango=0;
            try {
                CsvReader leer = new CsvReader(this.jLabel_direccion.getText());
                while (leer.readRecord()) rango++; leer.close();
            }catch (FileNotFoundException ex) {} catch (IOException ex) {}
            
        }
        
        File file = new File(this.jLabel_direccion.getText());
        
        int campo = -1;         //Inicializando
        if(this.jRadioButton_numerico.isSelected())
            campo = 0;
        else if(this.jRadioButton_texto.isSelected())
            campo = 1;
        else if(this.jRadioButton_booleano.isSelected())
            campo = 2;
        else if(this.jRadioButton_fecha.isSelected())
            campo = 3;
        else
        {
            JOptionPane.showMessageDialog(null, "Error, seleccione el campo sobre el cual se va a Ordenar.", "Error !!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try 
        {
            tiempoTotal = 0;
            if(this.jRadioButton_directa.isSelected()){
                OrdenamientoDirecto.Procesar(campo, file);
                long fin = System.nanoTime();
                double dif = (double)(fin - inicio)*1.0e-9;
                System.out.println("El Programa Dura: "+ dif +"  segundos");
                String difString = Double.toString(dif);
                this.jLabel_mostrarTiempo.setText(difString+"  segundos");
                jLabel_tiempoReloj.setText("" + getTiempo(this.tiempoTotal));
                JOptionPane.showMessageDialog(null,"Archivo Ordenado");
            }
                
            else if(this.jRadioButton_natural.isSelected()){
                OrdenamientoNatural.Procesar(campo, file);
                long fin = System.nanoTime();
                double dif = (double)(fin - inicio)*1.0e-9;
                System.out.println("El Programa Dura: "+ dif +"  segundos");
                String difString = Double.toString(dif);
                this.jLabel_mostrarTiempo.setText(difString+"  segundos");
                jLabel_tiempoReloj.setText("" + getTiempo(this.tiempoTotal));
                JOptionPane.showMessageDialog(null,"Archivo Ordenado");
            }
                
            else if(this.jRadioButton_balanceada.isSelected()){
                OrdenamientoBalanceado.Procesar(campo, file);
                long fin = System.nanoTime();
                double dif = (double)(fin - inicio)*1.0e-9;
                System.out.println("El Programa Dura: "+ dif +"  segundos");
                String difString = Double.toString(dif);
                this.jLabel_mostrarTiempo.setText(difString+"  segundos");
                jLabel_tiempoReloj.setText("" + getTiempo(this.tiempoTotal));
                JOptionPane.showMessageDialog(null,"Archivo Ordenado");
            }
                
            else if(this.jRadioButton_poliface.isSelected()){
                
                OrdenamientoPolifase.Procesar(campo, this.jLabel_direccion.getText());
                long fin = System.nanoTime();
                double dif = (double)(fin - inicio)*1.0e-9;
                System.out.println("El Programa Dura: "+ dif +"  segundos");
                String difString = Double.toString(dif);
                this.jLabel_mostrarTiempo.setText(difString+"  segundos");
                jLabel_tiempoReloj.setText("" + getTiempo(this.tiempoTotal));
                JOptionPane.showMessageDialog(null,"Archivo Ordenado");
                
            }
            else
                JOptionPane.showMessageDialog(null, "Error, por favor seleccione el algoritmo sobre el cual se\n va a realizar el ordenamiento.", "Error al procesar", JOptionPane.ERROR_MESSAGE);

        } 
        catch (IOException ex) {
            Logger.getLogger(interfaz_principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(interfaz_principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_JButton_ordenarArchivoActionPerformed

    private void jRadioButton_naturalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_naturalActionPerformed
        if (this.jRadioButton_directa.isSelected() || this.jRadioButton_balanceada.isSelected() || this.jRadioButton_poliface.isSelected() )
        {
            this.jRadioButton_directa.setSelected(false);
            this.jRadioButton_balanceada.setSelected(false);
            this.jRadioButton_poliface.setSelected(false);
        }
        
        this.jLabel_intercalacion.setText("Natural");
        
        
    }//GEN-LAST:event_jRadioButton_naturalActionPerformed

    private void jRadioButton_balanceadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_balanceadaActionPerformed
        if (this.jRadioButton_natural.isSelected() || this.jRadioButton_directa.isSelected() || this.jRadioButton_poliface.isSelected() )
        {
            this.jRadioButton_natural.setSelected(false);
            this.jRadioButton_directa.setSelected(false);
            this.jRadioButton_poliface.setSelected(false);
        }
        this.jLabel_intercalacion.setText("Balanceada");
        
    }//GEN-LAST:event_jRadioButton_balanceadaActionPerformed

    private void jRadioButton_polifaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_polifaceActionPerformed
        if (this.jRadioButton_natural.isSelected() || this.jRadioButton_balanceada.isSelected() || this.jRadioButton_directa.isSelected() )
        {
            this.jRadioButton_natural.setSelected(false);
            this.jRadioButton_balanceada.setSelected(false);
            this.jRadioButton_directa.setSelected(false);
            
        }
        this.jLabel_intercalacion.setText("Polifase");
        
    }//GEN-LAST:event_jRadioButton_polifaceActionPerformed

    private void jRadioButton_textoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_textoActionPerformed
        if (this.jRadioButton_numerico.isSelected() || this.jRadioButton_booleano.isSelected() || this.jRadioButton_fecha.isSelected())
        {
            this.jRadioButton_numerico.setSelected(false);
            this.jRadioButton_booleano.setSelected(false);
            this.jRadioButton_fecha.setSelected(false);
        }
        this.jLabel_mostrarCampo.setText("Texto");
    }//GEN-LAST:event_jRadioButton_textoActionPerformed

    private void jRadioButton_booleanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_booleanoActionPerformed
        if (this.jRadioButton_texto.isSelected() || this.jRadioButton_numerico.isSelected() || this.jRadioButton_fecha.isSelected())
        {
            this.jRadioButton_texto.setSelected(false);
            this.jRadioButton_numerico.setSelected(false);
            this.jRadioButton_fecha.setSelected(false);
        }
        this.jLabel_mostrarCampo.setText("Booleano");
    }//GEN-LAST:event_jRadioButton_booleanoActionPerformed

    private void jRadioButton_fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_fechaActionPerformed
        if (this.jRadioButton_texto.isSelected() || this.jRadioButton_booleano.isSelected() || this.jRadioButton_numerico.isSelected())
        {
            this.jRadioButton_texto.setSelected(false);
            this.jRadioButton_booleano.setSelected(false);
            this.jRadioButton_numerico.setSelected(false);
        }
        this.jLabel_mostrarCampo.setText("Fecha: dia/mes/año");
    }//GEN-LAST:event_jRadioButton_fechaActionPerformed

    private void jButton_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton_salirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        interfaz_verContenido verContenido =new interfaz_verContenido();
        verContenido.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButton_buscarArchivo;
    private javax.swing.JButton JButton_ordenarArchivo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_campo;
    public static javax.swing.JLabel jLabel_direccion;
    private javax.swing.JLabel jLabel_intercalacion;
    private javax.swing.JLabel jLabel_mostrarCampo;
    private javax.swing.JLabel jLabel_mostrarTiempo;
    private javax.swing.JLabel jLabel_tiempoReloj;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton_balanceada;
    private javax.swing.JRadioButton jRadioButton_booleano;
    private javax.swing.JRadioButton jRadioButton_directa;
    private javax.swing.JRadioButton jRadioButton_fecha;
    private javax.swing.JRadioButton jRadioButton_natural;
    private javax.swing.JRadioButton jRadioButton_numerico;
    private javax.swing.JRadioButton jRadioButton_poliface;
    private javax.swing.JRadioButton jRadioButton_texto;
    // End of variables declaration//GEN-END:variables
}
